AI4EOSC_PAPI_URL = 'http://localhost:8080'
envvar_AI4EOSC_PAPI_URL = 'AI4EOSC_PAPI_URL'
envvar_AI4EOSC_PAPI_TOKEN = 'AI4EOSC_PAPI_TOKEN'
envvar_AI4EOSC_DEFAULT_VO = 'AI4EOSC_DEFAULT_VO'
envvar_OIDC_AGENT_ACCOUNT = 'OIDC_AGENT_ACCOUNT'
envvar_OIDC_ACCESS_TOKEN = 'OIDC_ACCESS_TOKEN'
envvar_AI4EOSC_MYTOKEN = 'AI4EOSC_MYTOKEN'
envvar_AI4EOSC_MYTOKEN_SERVER = 'AI4EOSC_MYTOKEN_SERVER'
application_hint = 'ai4eosc_client'
MIN_ACCESS_TOKEN_TIME = 30  # minimum token time is 30 sec
logName = 'ai4eosc_client'
apiLogFormat = '%(levelname)-8s %(name)-12s %(asctime)s %(message)s'
mytoken_default_server=None
